### ISSUE TITLE
Add Cachy CPU Scheduler

### ISSUE THREAD

**Issue by m0lese** [m0lese/Linux-PamPeg#4]
VCS Upstream: [hamadmarri/cacule-cpu-scheduler](https://github.com/hamadmarri/cacule-cpu-scheduler)

**Comment by hamadmarri** [comment]
Hi @m0lese 

You don't really need cachy scheduler. It is replaced with cacule. I recommend you have cacule and cacule+rdb as a variation.

Thanks

**Comment by m0lese** [comment]
Gotcha!
